### ISSUE TITLE
Secure plugin breaks config

### ISSUE THREAD

**Issue by alexandreStein** [labstack/armor#24]
Hi,

I tried to active the secure plugin and It seems to break the HTTP2 connexion.
I leaved the plugin with default settings and even with the simplest configuration it's not working.

This goes to a go panic.

Am I doing something wrong?

**Comment by vishr** [comment]
Can you provide sample config?

**Comment by alexandreStein** [comment]
For example:
```yaml
address:        :80
read_timeout:   300
write_timeout:  300
tls:
  address:    :443
  auto:       true
  cache_dir:  /var/www/
hosts:
  example.com:
    plugins:
    - name: secure
```
Or:
```yaml
address:        :80
read_timeout:   300
write_timeout:  300
tls:
  address:    :443
  auto:       true
  cache_dir:  /var/www/
plugins:
- name: secure
hosts:
  example.com:
    plugins:
    - name: static
      root: /var/www/site
```

Both are not working.
I'm using the docker image. I just add the configuration file and some package for debugging.
You should be able to reproduce this error.

Here is my Dockerfile to reproduce the error.:
```dockerfile
FROM labstack/armor

RUN apk add --no-cache curl nmap

EXPOSE 80 443
WORKDIR /var/www/

ENTRYPOINT ["armor", "-c", "/etc/armor/config.yaml"]

COPY ./config.yaml /etc/armor/config.yaml
```

The server start without issue. But when you send a request to the server, it fails.
Maybe, I just misuse the plugin.

**Comment by vishr** [comment]
@alexandreStein Can you try the most recent release? https://github.com/labstack/armor/releases/tag/0.3.5

**Comment by alexandreStein** [comment]
I updated the docker image to 0.3.5 and it behaves the same way.

When I start the server I see that the starting message appears twice.
One with label 0.3.5 and an other with label 3.2.6: (the ports are weird too)
```
   ___                     
  / _ | ______ _  ___  ____
 / __ |/ __/  ' \/ _ \/ __/
/_/ |_/_/ /_/_/_/\___/_/    v0.3.5

Uncomplicated, modern HTTP server
https://armor.labstack.com
________________________O/_______
                        O\
⇨ http server started on :80
⇨ https server started on :443

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.2.6
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:8081
```

The error is:
```
echo: http2: panic serving 172.17.0.1:60026: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc42000c270, 0xc42003efaf, 0xc4200968c0)
	/usr/local/opt/go/libexec/src/net/http/h2_bundle.go:5740 +0x190
panic(0x7a7120, 0xa17c20)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/labstack/armor/plugin.(*Secure).Process(0xc42008cc80, 0xc42000fd70, 0xc420126e20)
	/Users/vr/Projects/labstack/armor/src/github.com/labstack/armor/plugin/secure.go:24 +0x2f
github.com/labstack/armor.(Plugin).Process-fm(0xc42000fd70, 0xc42000fd70)
	/Users/vr/Projects/labstack/armor/src/github.com/labstack/armor/armor.go:95 +0x39
github.com/labstack/armor/vendor/github.com/labstack/echo.(*Echo).ServeHTTP.func1(0x9f3a00, 0xc420120af0, 0x0, 0x0)
	/Users/vr/Projects/labstack/armor/src/github.com/labstack/armor/vendor/github.com/labstack/echo/echo.go:572 +0xc6
github.com/labstack/armor/http.Init.func1.1(0x9f3a00, 0xc420120af0, 0xc42006d3d8, 0x812860)
	/Users/vr/Projects/labstack/armor/src/github.com/labstack/armor/http/http.go:56 +0xea
github.com/labstack/armor/vendor/github.com/labstack/echo.(*Echo).ServeHTTP(0xc42006d380, 0x9ec720, 0xc42000c270, 0xc42011a400)
	/Users/vr/Projects/labstack/armor/src/github.com/labstack/armor/vendor/github.com/labstack/echo/echo.go:583 +0x28a
net/http.serverHandler.ServeHTTP(0xc4201160d0, 0x9ec720, 0xc42000c270, 0xc42011a400)
	/usr/local/opt/go/libexec/src/net/http/server.go:2619 +0xb4
net/http.initNPNRequest.ServeHTTP(0xc420132000, 0xc4201160d0, 0x9ec720, 0xc42000c270, 0xc42011a400)
	/usr/local/opt/go/libexec/src/net/http/server.go:3164 +0x9a
net/http.(*initNPNRequest).ServeHTTP(0xc420126d00, 0x9ec720, 0xc42000c270, 0xc42011a400)
	<autogenerated>:1 +0x63
net/http.(Handler).ServeHTTP-fm(0x9ec720, 0xc42000c270, 0xc42011a400)
	/usr/local/opt/go/libexec/src/net/http/h2_bundle.go:5462 +0x4d
net/http.(*http2serverConn).runHandler(0xc4200968c0, 0xc42000c270, 0xc42011a400, 0xc42014fd00)
	/usr/local/opt/go/libexec/src/net/http/h2_bundle.go:5747 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/opt/go/libexec/src/net/http/h2_bundle.go:5481 +0x495
```

And the configuration is pretty basic:
``` yaml
address: ":80"
read_timeout: 3600
write_timeout: 3600
tls:
  address: ":443"
  auto: true
  cache_dir: /var/www/
plugins:
- name: secure
hosts:
  dom.com:
    paths:
      "/":
        plugins:
        - name: static
          root: /var/test
```

If I remove the `secure` plugging it works normally.
